//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Resourses {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practica.Resourses.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required fields.
        /// </summary>
        internal static string Campos_requeridos {
            get {
                return ResourceManager.GetString("Campos requeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Count.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity to buy.
        /// </summary>
        internal static string Cantidad_a_comprar {
            get {
                return ResourceManager.GetString("Cantidad a comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billboard.
        /// </summary>
        internal static string Cartelera {
            get {
                return ResourceManager.GetString("Cartelera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cinema.
        /// </summary>
        internal static string Cinema {
            get {
                return ResourceManager.GetString("Cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalize purchase.
        /// </summary>
        internal static string Finalizar_compra {
            get {
                return ResourceManager.GetString("Finalizar compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Function.
        /// </summary>
        internal static string Funcion {
            get {
                return ResourceManager.GetString("Funcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Functions.
        /// </summary>
        internal static string Funciones {
            get {
                return ResourceManager.GetString("Funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Great.
        /// </summary>
        internal static string Genial {
            get {
                return ResourceManager.GetString("Genial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter amount of tickets.
        /// </summary>
        internal static string Ingresa_cantidad_de_boletas {
            get {
                return ResourceManager.GetString("Ingresa cantidad de boletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The minimum quantity is one.
        /// </summary>
        internal static string La_cantidad_minima_es_uno {
            get {
                return ResourceManager.GetString("La cantidad minima es uno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The reservation was generated successfully.
        /// </summary>
        internal static string La_reserva_se_ha_generado_correctamente {
            get {
                return ResourceManager.GetString("La reserva se ha generado correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not authorized.
        /// </summary>
        internal static string No_estas_autorizado {
            get {
                return ResourceManager.GetString("No estas autorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movie.
        /// </summary>
        internal static string Pelicula {
            get {
                return ResourceManager.GetString("Pelicula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase Summary.
        /// </summary>
        internal static string Resumen_compra {
            get {
                return ResourceManager.GetString("Resumen compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room.
        /// </summary>
        internal static string Sala {
            get {
                return ResourceManager.GetString("Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tickets.
        /// </summary>
        internal static string Tiquetes {
            get {
                return ResourceManager.GetString("Tiquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total to pay.
        /// </summary>
        internal static string Total_a_pagar {
            get {
                return ResourceManager.GetString("Total a pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
